import VersoManual
import TrilemmaBook.Ch01_Diagonal
open Verso.Genre Manual
open Verso.Genre.Manual.InlineLean

set_option pp.rawOnError true

#doc (Manual) "Watermarks, Paraphrase, and the Third Corner" =>

The three preceding chapters put a probe inside a model. This one steps outside
it entirely. The question is whether a piece of text was produced by a language
model, and the dominant answer is watermarking: bias the model's sampling so
that its output carries a statistical signature only a holder of the key can
detect. The construction is elegant, it is deployed, and it has a well-known
weakness, which is that paraphrasing the text tends to remove the signature.

That weakness is usually treated as an engineering race. Better watermarks
survive more aggressive paraphrase; better paraphrasers defeat more robust
watermarks; the literature reports empirical trade-off curves and the frontier
moves. This chapter argues the race has a fixed point, and locates it with a
mechanism the book has not used yet. Neither the diagonal nor the intermediate
value theorem is the primary tool here. The primary tool is invariance under a
group action, and the resulting theorem is a genuine trilemma in the book's
title sense: three properties, any two available, never all three.

The chapter then shows what the other two engines add. The analytic engine
supplies the quantitative version, converting the trilemma into a statement
about how many edits an attacker needs. The diagonal supplies something specific
to this domain and absent from Chapters 8 through 10: here the surjectivity
hypothesis is not an idealization at all, because a public detection API hands
the attacker exactly the oracle the diagonal argument requires.

# The construction

*Definition 11.1 (Text space and marking).* Write `X` for the space of
texts. Write `mark : X → Bool` for the fact of the matter, `mark x = true` when
`x` was generated by the watermarked model. As in Chapter 9 this is ground
truth, not something anyone computes.

*Definition 11.2 (Detector).* A *detector* is a map
`det : X → Bool`, returning `true` when it judges the text to carry the mark. In
practice `det` thresholds a statistic, typically a count of tokens falling in a
pseudorandomly chosen green list, against a null distribution.

*Definition 11.3 (Paraphrase).* A *paraphrase map* is a function
`par : X → X` sending a text to one that means the same thing. What
*means the same thing* amounts to is doing real work in this definition,
and we return to it in the honest accounting at the end. For the theorems below
the only thing that matters about `par` is that it is a map on `X` which
preserves whatever downstream property makes the text useful.

The three properties a detector is asked to have:

*Definition 11.4 (Sound).* A detector is *sound* when it never flags
unmarked text: `mark y = false → det y = false`. Soundness is the property whose
failure produces a false accusation, and it is the one with the most direct
human cost, since the unmarked texts are the ones people wrote.

*Definition 11.5 (Complete).* A detector is *complete* when it flags
all marked text: `mark y = true → det y = true`. Completeness is what the
watermark is for.

*Definition 11.6 (Robust).* A detector is *robust* against `par` when
paraphrasing does not change its verdict: `det (par x) = det x` for all `x`.
Robustness is the property the empirical literature measures as the detection
rate surviving a paraphrase attack, stated here in its exact limit.

```lean
def c11_Sound {X : Type _} (det mark : X → Bool) : Prop :=
  ∀ y, mark y = false → det y = false

def c11_Complete {X : Type _} (det mark : X → Bool) : Prop :=
  ∀ y, mark y = true → det y = true

def c11_Robust {X : Type _} (det : X → Bool) (par : X → X) : Prop :=
  ∀ x, det (par x) = det x
```

One more ingredient, and it is the empirical fact the whole subject is organized
around. A paraphraser can take marked text to unmarked text. This is not an
assumption about detectors; it is a statement about what paraphrasing does to a
statistical signature carried by token choices, and it is what every reported
paraphrase attack demonstrates.

*Definition 11.7 (Stripping).* A paraphrase map *strips* the mark at
`x` when `mark x = true` and `mark (par x) = false`.

# The trilemma

*Theorem 11.8 (Detection trilemma).* *No detector is sound, complete, and
robust against a paraphrase map that strips the mark.*

```lean
theorem c11_detection_trilemma {X : Type _}
    (det mark : X → Bool) (par : X → X)
    (hsound : c11_Sound det mark) (hcomplete : c11_Complete det mark)
    (hrobust : c11_Robust det par)
    (x : X) (hmark : mark x = true) (hstrip : mark (par x) = false) :
    False := by
  have h1 : det x = true := hcomplete x hmark
  have h2 : det (par x) = false := hsound (par x) hstrip
  rw [hrobust x, h1] at h2
  exact Bool.noConfusion h2
```

*Proof.* Completeness flags `x`, since it is marked. Soundness clears `par x`,
since it is not. Robustness says those two verdicts are the same verdict. So
`true = false`. ∎

The proof is four lines and uses no self-reference, no topology, and no
assumption about the size or structure of `X`. What makes it a trilemma rather
than a curiosity is that each of the three hypotheses is individually
achievable, and dropping any one leaves a working system. It is worth walking
the three corners, because each is a real deployment and the reader will
recognize all of them.

*Give up robustness.* Keep soundness and completeness, and accept that
paraphrase defeats detection. This is the honest state of most deployed
watermarking today, and it is a coherent position: the watermark then detects
unmodified output, which covers casual use and not adversarial use. The failure
mode is that the population you most want to detect is exactly the population
willing to run a paraphraser.

*Give up completeness.* Keep soundness and robustness, and accept that
some marked text goes unflagged. This is what raising the detection threshold
does. It is the right corner for high-stakes accusations, since it never
accuses the innocent, and it is what a court would want. The failure mode is
that the detector's silence carries no information.

*Give up soundness.* Keep completeness and robustness, and accept false
positives on human writing. This corner is the one nobody defends explicitly and
several systems occupy accidentally: a detector tuned aggressively enough to
survive paraphrase is a detector flagging text whose statistics merely resemble
the model's, and human writing that resembles model writing is common, since the
model was trained to produce writing that resembles ours.

*Remark 11.9 (Why this is the book's shape and not an analogy).* Chapter 3
showed the hallucination and defense trilemmata are one theorem with three
readings. Theorem 11.8 is not that theorem, and it would be overclaiming to say
so: its mechanism is invariance and its proof is not the diagonal. What it
shares with Chapter 3 is the *form* of the conclusion, three desiderata
with a forced choice of two, and the reason the form recurs is worth naming. In
Chapter 3 the third property was destroyed by a fixed-point-free flip. Here it
is destroyed by an orbit: `par` moves a point while `det` is required to stay
put, and `mark` is required to move. Any time a system must be invariant along a
motion that changes the truth, the same three-cornered choice appears.

*Corollary 11.10 (Invariance and truth cannot both hold along an orbit).*
*If `det` is constant along `par` and `mark` is not, then `det` does not
agree with `mark` everywhere.*

```lean
theorem c11_invariance_vs_truth {X : Type _}
    (det mark : X → Bool) (par : X → X)
    (hinv : ∀ x, det (par x) = det x)
    (x : X) (hne : mark (par x) ≠ mark x) :
    ¬ (∀ y, det y = mark y) :=
  fun h => hne (by rw [← h (par x), ← h x, hinv x])
```

*Proof.* If the detector agreed with the mark everywhere, rewrite both sides of
`mark (par x) = mark x` into detector values; invariance closes it, contradicting
the assumption that the mark moves. ∎

This is Theorem 11.8 with the watermarking vocabulary stripped out: a fact about
functions on a set carrying a self-map, of which the watermarking reading is one
instantiation. Chapter 5's attack basins are another, which is the connection
the next section makes quantitative.

# The diagonal, and why its price is low here

Chapters 8 through 10 were careful to concede that point-surjectivity is an
idealization for a fixed network. This chapter does not need that concession,
and the reason is worth stating clearly, because it makes the diagonal argument
stronger here than anywhere else in the book except prompt injection.

A detector is useful only if someone can run it. Deployed detection is offered
as an API, or as a published statistic with a published threshold, or as a tool
handed to a platform. Whichever it is, an attacker who can call it can measure
its verdict on any text, and an attacker who can measure a verdict can construct
a text achieving whatever verdict pattern it likes, by generating candidates and
querying. Text is unrestricted, self-describing, and cheap to produce in
quantity. The surjectivity hypothesis, which for a J-space probe is a limit
statement about a finite network, is here a description of an afternoon's work.

*Theorem 11.11 (An adaptive attacker finds the liar text).* *If every
pattern of verdicts over texts is realized by some text, there is a text whose
verdict is its own negation.*

```lean
theorem c11_detector_liar {X : Type _} (det : X → X → Bool)
    (hs : ∀ g : X → Bool, ∃ t, det t = g) :
    ∃ t, det t t = !(det t t) :=
  liar_query det hs
```

*Proof.* {lean}`liar_query` applied to the detector read as a self-verdict. ∎

The reading of `det t s` here is the detector's verdict on text `s` when the
detector has been configured, tuned, or prompted by text `t`, which is the
situation for any detector that is itself a language model, and for any detector
whose threshold is set from a corpus an attacker can influence. The diagonal
text is one that describes the detector's own behavior and inverts it.

*Theorem 11.12 (Detector composition does not help).* *Routing the verdict
through any preprocessing stage leaves the impossibility intact.*

```lean
theorem c11_pipeline_no_escape {X F : Type _}
    (feat : X → F) (det : F → X → Bool)
    (hs : ∀ g : X → Bool, ∃ t, det (feat t) = g) : False :=
  no_reflective_verdict (fun t => det (feat t)) hs
```

*Proof.* The composite is a reflective verdict. ∎

Theorem 11.12 is the Chapter 8 argument in this domain, and it covers the family
of proposals that extract features first, whether those are perplexity
statistics, stylometric vectors, or a learned embedding. The extraction is a
representation, and Chapter 8 established that representations do not rescue
verdicts.

# The analytic engine, and the cost of an attack

The trilemma is exact and says nothing about degree. Real detectors return a
score and real paraphrasers make bounded edits, and the interesting engineering
question is how many edits it takes. This is Chapter 5's subject, and it applies
here with unusually concrete units.

Let `s : X → ℝ` be the detector's score, with `det x = true` exactly when
`s x > τ`. Suppose the text space carries an edit distance, and suppose the
score is Lipschitz with respect to it, which is the formal content of the
requirement that a single word substitution cannot swing the statistic wildly.
Then the argument of Chapter 5 runs verbatim. A marked text sits at score
`s x > τ`, an unmarked paraphrase sits below, and the path of intermediate
edits between them is connected, so the score crosses `τ`. The crossing text is
the ambiguous case, and the number of edits needed to reach it from `x` is
bounded below by `(s x − τ)/L` where `L` is the Lipschitz constant.

That inequality is the whole quantitative theory of watermark robustness in one
line, and it has the right qualitative behavior in both variables. Strengthening
the watermark raises `s x` and so raises attack cost, which is why more
aggressive green-list biasing is more robust. Making the detector smoother
lowers `L` and also raises attack cost, which is why aggregating over longer
spans helps. And both moves trade against the two other corners: raising `s x`
means biasing the sampler harder, which degrades text quality, and lowering `L`
means a detector less sensitive to short texts, which costs completeness on
exactly the short outputs that are cheapest to produce.

So the exact trilemma and the quantitative law say the same thing at different
resolutions. Theorem 11.8 says the three corners cannot all be occupied. The
Lipschitz bound says how far from the third corner a given design sits, and
prices the distance in edits. Chapter 6's approximate bridges are what connect
them: the exact statement is the zero-slack corner of the quantitative family,
and no deployed system lives there.

# What this does not claim

It does not claim watermarking is pointless. Theorem 11.8 is a statement about
the three exact corners, and the useful deployments live at the corners the
theorem leaves open. A watermark that detects unmodified output soundly and
completely is a real capability with real applications, and giving up robustness
is a coherent design decision rather than a failure.

It does not claim paraphrase is free. The whole content of the analytic section
is that stripping the mark has a cost, that the cost is computable from the
detector's own parameters, and that raising it is the legitimate goal of
watermark design. The trilemma says the cost cannot be made infinite; it does
not say it cannot be made high.

It does not settle what `par` is. Definition 11.3 asks that a paraphrase
preserve meaning, and no formalization here says what that amounts to. This
matters: a paraphraser that degrades the text until it is useless has not
defeated the detector in any sense that concerns anyone. A serious treatment
would carry a utility function on texts and require the paraphrase to preserve
it above a floor, which is exactly the structure of the Defense Trilemma in
Chapter 3, and the two results would then be instances of one statement. That
unification is not attempted here.

It does not claim the stripping hypothesis holds for every watermark. Theorem
11.8 needs a paraphrase that actually removes the mark at some text. A scheme
whose signature survives every meaning-preserving edit would escape the theorem,
and no theorem in this book rules such a scheme out. What can be said is that
the signature must then be carried by something no meaning-preserving edit
touches, and it is not currently known what that would be.

# Exercises

*Exercise 11.1.* Prove the three one-corner-dropped versions of Theorem 11.8:
for each pair of the three properties, exhibit a detector satisfying that pair
in the presence of a stripping paraphrase.

*Exercise 11.2.* Prove {lean}`c11_detection_trilemma` in term mode without
tactics, using `Bool.noConfusion` directly on a chain of `Eq.trans`.

*Exercise 11.3.* Generalize Corollary 11.10: state and prove that if `det` is
constant on the orbit of `x` under iterated `par` and `mark` is not, the
conclusion holds, without assuming a single application strips the mark.

*Exercise 11.4.* Formalize a bounded paraphrase as a map with an edit budget,
and state the version of Theorem 11.8 in which robustness is required only
within the budget. What replaces the stripping hypothesis?

*Exercise 11.5.* Add a utility function `u : X → Bool` to Definition 11.3 and
require `u (par x) = u x`. State the resulting four-property theorem and
compare it to the Defense Trilemma of Chapter 3.

*Exercise 11.6.* (Analytic, prose.) Derive the edit-count bound
`(s x − τ)/L` carefully, stating the hypotheses on the edit metric that the
argument needs, and explain which of them fails for very short texts.

*Exercise 11.7.* (Design.) You must choose a corner for a platform that
moderates user submissions. Argue for one, name the population your choice
fails, and give the measurement that would tell you the failure rate in
deployment.
